
__global_clicked=false;no_folder_info=opener.util_defaultValue(opener.$KTML4_GLOBALS['no_folder_info'],'')+''=='true';FolderTree=function(ktml,container,target_path){KTStorage.add(this);lang_subfolders=topOpener.translate("subfolders")
lang_files=topOpener.translate("files")
var this_id=this.id;this.ktml=ktml;this.container=container;if(typeof(this.container)=="string"){this.container=document.getElementById(this.container);}
this.item=utility.dom.getElementsByClassName(this.container,"fl_container","div")[0];this.item.innerHTML='';this.item.tree_id=this_id;this.container.tree_id=this_id;utility.dom.attachEvent(this.container,'onclick',function(){if(__global_clicked){__global_clicked=false;return false;};KTStorage.get(this_id).select_path("/");});if(typeof(target_path)=="undefined"){target_path="/";}
target_path=target_path.replace(/^\/+/,"/");this.selected_path="";this.root=new FolderTreeItem(this.id,this,"/");this.root.items=this.root.item;this.item.appendChild(this.root.item);this.items=this.item;this.select_path(target_path);};FolderTree.prototype.trigger_event=function(event_name){var evfn;var args=new Array(arguments.length-1);for(var i=1;i<arguments.length;i++){args[i-1]=arguments[i];}
evfn=this[event_name];if(typeof(evfn)=="function"){evfn.apply(this,args);}};FolderTree.toggle_node=function(id,e){utility.dom.stopEvent(e);var node=KTStorage.get(id);if(node.isOpen){node.close();}else{if(node.subfolders>0){node.open();}else{node.setOpen();}}
return false;};FolderTree.select_node=function(id,e){var node=KTStorage.get(id);utility.dom.stopEvent(e);KTStorage.get(node.tree_id).select_path(node.path);};FolderTree.prototype.path_to_node=function(target_path,block){var crt,i,parts,idx;crt=this.root;parts=target_path.split("/");for(i=1;i<parts.length;i++){if(crt.path<target_path){idx=crt.getChildIndexByName(parts[i]);if(idx>=0){crt=crt.children[idx];}else{return crt;}}}
return crt;};FolderTree.prototype.open_path=function(target_path,block){target_path=target_path.replace(/^\/+/,"/");var crt,i,parts,idx;crt=this.root;parts=target_path.split("/");for(i=1;i<parts.length;i++){if(crt.isOpen){if(crt.path<target_path){idx=crt.getChildIndexByName(parts[i]);if(idx>=0){crt=crt.children[idx];}else{return;}}}else{tree=this;crt.open(function(path){tree.open_path(target_path,block);});return;}}
if(typeof(block)=="function")block(crt);};FolderTree.prototype.close_path=function(target_path,block){var node;node=this.path_to_node(target_path);node.close();if(typeof(block)=="function")block(node);};FolderTree.prototype.select_path=function(target_path,block){var parts,toselect,tree;tree=this;target_path=target_path.replace(/^\/+/,"/");if(target_path=="/"){this.open_path("/",function(){tree.root.select();if(typeof(block)=="function")block();});}else{parts=target_path.split("/");toselect=parts[parts.length-2];parts.splice(parts.length-2,1);this.open_path(parts.join("/"),function(node){node.selectChild(toselect);var idx;idx=node.getChildIndexByName(toselect);if(typeof(block)=="function")block();});}};FolderTree.prototype.cd_up=function(){this.select_path(this.selected_path.replace(/[^\/]+\/$/,""));};FolderTree.prototype.mkdir=function(name,block){var tree,node,toadd;tree=this;node=this.path_to_node(this.selected_path);toadd=this.selected_path+name+"/";this.ktml.makeRequest("folder","create",{"folder":toadd,"submode":browse_submode},function(result){if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));if(typeof(block)=="function")block();return;}
if(node.childrenStatus>1){node.addChild(name,{"subfolders":0,"allfiles":0},true);}
node.setDetails({"subfolders":node.subfolders+1,"allfiles":node.allfiles,"filteredfiles":node.filteredfiles});if(typeof(block)=="function")block();});};FolderTree.prototype.rmdir=function(path,block){var tree,node,toadd,parent;if(path==""){path=this.selected_path;}
if(path=="/")return;tree=this;node=this.path_to_node(this.selected_path);tree.ktml.makeRequest("folder","delete",{"folder":path,"submode":browse_submode},function(result){if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
parent=node.parent;parent.removeChild(node.name);parent.select();parent.setDetails({"subfolders":parent.subfolders-1,"allfiles":parent.allfiles,"filteredfiles":parent.filteredfiles});if(typeof(block)=="function")block();});};FolderTree.prototype.markforcut=function(item){node=this.path_to_node(item);node.markforcut();};FolderTree.prototype.dispose=function(){this.root.dispose();this.item=null;this.items=null;this.container=null;};FolderTreeItem=function(tree_id,parent,path,result,create){KTStorage.add(this);this.tree_id=tree_id;this.parent=parent;this.path=path;var tmparr=this.path.split("/");this.name=tmparr[tmparr.length-2];this.type="Folder";this.isOpen=0;this.childrenStatus=0;this.children=[];if(typeof result=='undefined'){this.subfolders=0;this.allfiles=0;}else{this.subfolders=Number(result.subfolders);this.allfiles=Number(result.allfiles);this.filteredfiles=Number(result.filteredfiles);}
this.html=this.getHTML();this.items=null;if(typeof create=='undefined'){create=true;}
if(create||path=="/"){this.item=this.getAsElement();this.item.setAttribute("item_id",this.id);this.item.setAttribute("has_context_menu","true");}else{this.item=null;}};FolderTreeItem.prototype.getAsElement=function(val){var tmp=document.createElement("span");tmp.innerHTML=this.html;return tmp.firstChild;}
FolderTreeItem.prototype.setOpen=function(val){this.isOpen=val;this.setPlusMinus();};FolderTreeItem.prototype.getChildIndexByName=function(name){var i;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){return i;}}
return-1;};FolderTreeItem.prototype.open=function(block){var tmp;this.setOpen(1);if(this.childrenStatus>1){if(this.children.length>0){if(this.items.tagName=="TD"){utility.dom.showElem(this.items.parentNode);}else{utility.dom.showElem(this.items);}
KTStorage.get(this.tree_id).trigger_event("onnodeopen",this.path);}}
if(this.childrenStatus<=1){this.getChildren(block);}};FolderTreeItem.prototype.close=function(block){var tmp;if(this.path=="/")return;if(this.childrenStatus>1&&this.children.length>0){if(this.items.tagName=="TD"){utility.dom.hideElem(this.items.parentNode);}else{utility.dom.hideElem(this.items);}
KTStorage.get(this.tree_id).trigger_event("onnodeclose",this.path);}
this.setOpen(0);};FolderTreeItem.prototype.getChildren=function(block){var node=this;this.childrenStatus=1;if(this.items==null){var table=document.getElementById(this.id+'_table');if(table){var tr=table.insertRow(-1);if(this.subfolders==0){tr.style.display="none";}
var cell=tr.insertCell(-1);cell.innerHTML="&nbsp;";cell=tr.insertCell(-1);this.items=cell;}else{this.items=this.gitem();}}
if(this.subfolders>0||this.path=="/"){var tmp;tmp=document.createElement("div");tmp.className="fl_item_children loading";tmp.innerHTML=trans(i18n.LOADING);this.items.appendChild(tmp);}
KTStorage.get(this.tree_id).ktml.makeRequest("folder","read",{"folder":node.path,"submode":browse_submode,"what":"folders","filter":browse_filter},function(result){node.receiveChildren(result,block);});};FolderTreeItem.prototype.receiveChildren=function(result,block){var i;if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
var c=null;var s1=new Date();this.innerHTML='';var arr=[];for(i=0;i<result.length;i++){c=this.addChild(result[i].name,result[i],false);arr.push(c.html);}
this.innerHTML=arr.join("");this.items.innerHTML=this.innerHTML;if(is.mozilla&&!no_folder_info){this.thread_counter=0;var _this=this;setTimeout(function(){_this.ff_tooltips_thread();},100);}
if(this.children.length==0&&this.items.tagName=="TD"){this.items.parentNode.parentNode.parentNode.deleteRow(1);this.items=null;}
this.subfolders=this.children.length;this.setPlusMinus();KTStorage.get(this.tree_id).trigger_event("onnodeopen",this.path);this.childrenStatus=2;node=this;if(typeof(block)=="function")block(node.path);this.childrenStatus=3;};FolderTreeItem.prototype.ff_tooltips_thread=function(){for(var i=this.thread_counter;i<this.children.length&&i<this.thread_counter+17;i++){var tmp=document.getElementById(this.children[i].id+'_link');if(!tmp){continue;}
KT_Tooltips.attach_single(tmp);}
if(i<this.children.length){this.thread_counter=i;var _this=this;setTimeout(function(){_this.ff_tooltips_thread();},1);}}
FolderTreeItem.prototype.getHTML=function(){var title='';if(!no_folder_info){title=this.subfolders+" "+lang_subfolders+"\r\n"+this.filteredfiles+" "+lang_files;}
var ret='<div id="'+this.id+'" class=fl_item_container path="'+this.path+'" item_id="'+this.id+'"  has_context_menu="true">';if(this.path!="/"){ret+='<table id="'+this.id+'_table" class="fl_item" cellpadding="0" cellspacing="0" border="0"><tr valign="middle">';ret+='<td><div id="'+this.id+'_plus_minus" class="folder_item_plus_minus'+(no_folder_info||this.subfolders?' plus':'')+'" '+(no_folder_info||this.subfolders?'onclick="FolderTree_toggle_node(event)"':'')+'></div></td>';ret+='<td><div class="folder_item_item"><div tabindex="1" id="'+this.id+'_link" class="folder_icon" title="'+title+'"';ret+=' ondblclick="FolderTree.toggle_node(\''+this.id+'\', event)"';ret+=' onclick="preventQuickDeleteFlag = false; return FolderTree.select_node(\''+this.id+'\', event)"><span>'+this.name+'</span></div></div></td></tr></table>';}
ret+='</div>';return ret;}
FolderTreeItem.prototype.gitem=function(){if(!this.item){this.item=document.getElementById(this.id);}
return this.item;}
FolderTreeItem.prototype.addChild=function(name,result,create){if(typeof create=='undefined'){create=false;}
var i,tmp,added=false,new_child;if(this.items==null){var table=document.getElementById(this.id+'_table');if(table){var tr=table.insertRow(-1);var cell=tr.insertCell(-1);cell.innerHTML="&nbsp;";cell=tr.insertCell(-1);this.items=cell;}else{this.items=this.gitem();}}
new_child=new FolderTreeItem(this.tree_id,this,this.path+name+"/",result,create);for(i=0;create&&i<this.children.length;i++){if(name.toLowerCase()<this.children[i].name.toLowerCase()){this.children.splice(i,0,new_child);if(create){this.items.insertBefore(new_child.item,this.children[i+1].gitem());}
added=true;break;}}
if(!added){this.children.push(new_child);if(create){this.items.appendChild(new_child.item);}}
return new_child;};FolderTreeItem.prototype.removeChild=function(name){var i,tmp;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){tmp=document.getElementById(this.children[i].id);tmp.parentNode.removeChild(tmp);this.children.splice(i,1);if(this.children.length==0){if(this.path!="/"){this.items.parentNode.parentNode.parentNode.deleteRow(1);this.items=null;}}
return;}}};FolderTreeItem.prototype.selectChild=function(name,block){var idx;idx=this.getChildIndexByName(name);if(idx>=0){this.children[idx].select();}
if(typeof(block)=="function")block(path);};FolderTreeItem.prototype.select=function(){var tree=KTStorage.get(this.tree_id);if(tree.selected_path!=""){var node=tree.path_to_node(tree.selected_path);node.deselect();}
item_selection_type="folder";var tmp=document.getElementById(this.id+'_link');if(tmp){utility.dom.classNameAdd(tmp,"fl_selected");}
tree.selected_path=this.path;if(this!=tree.root){var c,cbox,dbox;c=tree.item.parentNode;cbox=utility.dom.getBox(c);dbox=utility.dom.getBox(tmp);if(is.mozilla){if((dbox.y-c.scrollTop)<=cbox.y){c.scrollTop=dbox.y-cbox.y-1;}else if((dbox.y+dbox.height-c.scrollTop)>(cbox.y+cbox.height-17)){c.scrollTop=dbox.y+dbox.height-cbox.y-cbox.height+4+17;}
if((dbox.x-c.scrollLeft)<=cbox.x){c.scrollLeft=dbox.x-cbox.x-17;}else if((dbox.x+112-c.scrollLeft)>(cbox.x+cbox.width)){c.scrollLeft=dbox.x+89-cbox.x-cbox.width+4;}}else{if((dbox.y)<=cbox.y){c.scrollTop=c.scrollTop+dbox.y-cbox.y;}else if((dbox.y+dbox.height)>(cbox.y+cbox.height-17)){c.scrollTop=c.scrollTop+dbox.y+dbox.height-cbox.y-cbox.height+4+17;}
if((dbox.x)<=cbox.x){c.scrollLeft=c.scrollLeft+dbox.x-cbox.x-17;}else if((dbox.x+112)>(cbox.x+cbox.width)){c.scrollLeft=c.scrollLeft+dbox.x+89-cbox.x-cbox.width+4;}}}
tree.trigger_event("onnodeselect",this.path);};FolderTreeItem.prototype.deselect=function(){var tmp,a,img;tmp=document.getElementById(this.id+'_link');if(tmp){utility.dom.classNameRemove(tmp,"fl_selected");}
KTStorage.get(this.tree_id).trigger_event("onnodedeselect",this.path);item_selection_type="none";return;};FolderTreeItem.prototype.dispose=function(){for(var i=0;i<this.children.length;i++){this.children[i].dispose();}
this.item=null;this.items=null;};FolderTree.prototype.op_one=function(op,src,block){var path=this.selected_path;if(op=="cut")op="move";this.ktml.makeRequest("folder",op,{"src":src,"dest":path},function(result){if(typeof(result)=='object'&&result.error){alert(utility.string.getInnerText(result.error.message));return;}
if(typeof(block)=="function")block(result,src);});};FolderTreeItem.prototype.markforcut=function(){if(!this.markedforcut){this.markedforcut=true;utility.dom.classNameAdd(this.gitem(),"thumbnail_cut");}};FolderTreeItem.prototype.unmarkforcut=function(){if(this.markedforcut){this.markedforcut=false;utility.dom.classNameRemove(this.gitem(),"thumbnail_cut");}};FolderTreeItem.prototype.setDetails=function(result){this.subfolders=Number(result.subfolders);this.allfiles=Number(result.allfiles);this.filteredfiles=Number(result.filteredfiles);var tmp=document.getElementById(this.id+'_link');if(!tmp){return;}
tmp.title=this.subfolders+" "+lang_subfolders+"\r\n"+this.filteredfiles+" "+lang_files;KT_Tooltips.attach_single(tmp);this.setPlusMinus();};FolderTreeItem.prototype.setPlusMinus=function(){var tmp,tmparr;if(this.path=="/")return;var tmp=document.getElementById(this.id+'_plus_minus');var my_id=this.id;if(this.children.length==0&&this.subfolders==0){tmp.className='folder_item_plus_minus none';tmp.onclick=function(){};}else{tmp.className='folder_item_plus_minus '+(this.isOpen?'minus':'plus');tmp.onclick=FolderTree_toggle_node;}};function FolderTree_toggle_node(event){var o=utility.dom.setEventVars(event);var target=o.targ;while(target){if(typeof target.className!='undefined'&&target.className=='fl_item_container'){break;}
target=target.parentNode;}
if(!target){return true;}
var fl_item_container=o.targ;FolderTree.toggle_node(target.id,event);__global_clicked=true;return false;}